#Ejemplo archivo docker-compose.yml
version: "3.9"
services:
  frontendreact:
    image: angelusa/frontend-react
    ports:
      - 80:3000
    volumes:
      - datafront:/app/src
    depends_on:
      - backendspring
  backendspring:
    image: angelusa/backend-springboot
    ports:
      - 8080:8080
volumes:
  datafront:
    